---
title: "DDS Case Study 2"
output: html_document
date: "2022-11-19"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,echo = TRUE)
```

## R Markdown

```{r}

#Link to Presentation
# https://www.youtube.com/watch?v=qFb8cKCTGag

```

```{r}


#GET ATTRITION DATA
library(tidyverse)
library(caret)
library(e1071)
library(class)
library(dplyr)
library(plotly)
library(ggthemes)
library(shiny)
library(ggplot2)
library(car)


#Read in attrition training data
attr_train_DF = read.csv("C:/Users/bejes/OneDrive/School/MSDS 6306 Doing Data Science/Github Resources/MSDS_6306_Doing-Data-Science-Master/Unit 14 and 15 Case Study 2/EmployeeAttritionAndSalaries/CaseStudy2-data.csv")

#Read in attrition test data
attr_test_DF = read.csv("C:/Users/bejes/OneDrive/School/MSDS 6306 Doing Data Science/Github Resources/MSDS_6306_Doing-Data-Science-Master/Unit 14 and 15 Case Study 2/EmployeeAttritionAndSalaries/CaseStudy2CompSet No Attrition.csv")

attr_train_DF$OverTime = ifelse(attr_train_DF$OverTime=="Yes",1,0)
attr_test_DF$OverTime = ifelse(attr_test_DF$OverTime=="Yes",1,0)
attr_train_DF$OverTime = as.numeric(attr_train_DF$OverTime)


attr_train_DF$Gender = ifelse(attr_train_DF$Gender=="Female",1,0)
attr_test_DF$Gender = ifelse(attr_test_DF$Gender=="Female",1,0)

attr_train_DF$logMonthlyIncome = log(attr_train_DF$MonthlyIncome)
attr_train_DF$logDailyRate = log(attr_train_DF$DailyRate)
attr_train_DF$logHourlyRate = log(attr_train_DF$HourlyRate)




attr_train_DF
attr_test_DF


```

#NB ALL COMBOS OF 3
```{r}
# 
# #CLASSIFYING USING NB
# iterations = 10
# 
# splitPercent = .75
# 
# resultsDataframe = data.frame(accuracy = double(), specificity = double(),sensitivity= double(), combination = character())
# 
# columnCombinations = c(2,5,7,8,10,12,13,14,15,16,18,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37)
# 
# row =0
# 
# for(i in 3){
#   columnCombinationsMatrix = combn(columnCombinations, i)
#   
#   for(j in 1:ncol(columnCombinationsMatrix)){
#     print(paste(j,"of",ncol(columnCombinationsMatrix)))
#     for(x in 1:iterations){
#       
#       yes_DF = attr_train_DF %>% filter(Attrition == "Yes")
#       no_DF = attr_train_DF %>% filter(Attrition == "No")
#       new_attr_train_DF = rbind(yes_DF,sample_n(no_DF,140))
#       
#       row = row+1
#     
#       trainIndices = sample(1:870,round(splitPercent*870))
#       train = new_attr_train_DF[trainIndices,]
#       test = new_attr_train_DF[-trainIndices,]
#           
#       model = naiveBayes(train[,columnCombinationsMatrix[,j]],train$Attrition)
#       CM = confusionMatrix(table(predict(model,test[,columnCombinationsMatrix[,j]]),test$Attrition))
#       
#       resultsDataframe[row,] = c(CM$overall[1],CM$byClass[2],CM$byClass[1],paste(columnCombinationsMatrix[,j],collapse = " ") ) 
#       x=x+1
#       
#     }
#     
#     
#   }
# }
# 
# resultsDataframe$specificity = as.numeric(resultsDataframe$specificity)
# 
# mean(resultsDataframe$specificity,na.rm=TRUE)
# max(resultsDataframe$specificity)
# 
# mean(resultsDataframe$sensitivity,na.rm=TRUE)
# max(resultsDataframe$sensitivity)
# 
# resultsDataframe[order(-resultsDataframe$specificity), ]
# 
# 
# write.csv(resultsDataframe, paste("C:/Users/BenjaminBerger/OneDrive - QualTek/Documents/School/Naive Bayes runs/Combos_of_3_10_Iterations_run2.csv"))
# 
# 
# ```
# #NB USING SPECIFIC TRIO
# ```{r}
# #CLASSIFYING USING NB
# iterations = 100
# 
# splitPercent = .75
# 
# resultsDataframe = data.frame(accuracy = double(), specificity = double(),sensitivity = double() )
# 
# row =0
# 
#     for(x in 1:iterations){
#       
#       yes_DF = attr_train_DF %>% filter(Attrition == "Yes")
#       no_DF = attr_train_DF %>% filter(Attrition == "No")
#       new_attr_train_DF = rbind(yes_DF,sample_n(no_DF,140))
#       
#       row = row+1
#     
#       trainIndices = sample(1:280,round(splitPercent*280))
#       train = new_attr_train_DF[trainIndices,]
#       test = new_attr_train_DF[-trainIndices,]
#           
#       model = naiveBayes(train[,c(15,29,37)],train$Attrition)
#       CM = confusionMatrix(table(predict(model,test[,c(15,29,37)]),test$Attrition))
#       
#       
#       resultsDataframe[row,] = c(CM$overall[1],CM$byClass[2],CM$byClass[1])
#       x=x+1
#     }
# 
# CM
# 
# resultsDataframe$specificity = as.numeric(resultsDataframe$specificity)
# 
# mean(resultsDataframe$specificity,na.rm=TRUE)
# max(resultsDataframe$specificity)
# 
# mean(resultsDataframe$sensitivity,na.rm=TRUE)
# max(resultsDataframe$sensitivity)
# 
# resultsDataframe[order(-resultsDataframe$specificity), ]
# 
# 
# #write.csv(resultsDataframe, paste("C:/Users/BenjaminBerger/OneDrive - QualTek/Documents/School/Naive Bayes runs/Combos_of_3_10_Iterations.csv"))



```

```{r}

#CLASSIFY REAL TEST SET

splitPercent = .75

yes_DF = attr_train_DF %>% filter(Attrition == "Yes")
no_DF = attr_train_DF %>% filter(Attrition == "No")
new_attr_train_DF = rbind(yes_DF,sample_n(no_DF,140))
      

trainIndices = sample(1:280,round(splitPercent*280))
train = new_attr_train_DF[trainIndices,]
test = new_attr_train_DF[-trainIndices,]
model = naiveBayes(train[,c(15,29,37)],train$Attrition)

attr_results_df = as.data.frame(predict(model,attr_test_DF[,c(14,28,35)]) )

attr_results_df$ID = attr_test_DF[,1]

names(attr_results_df) <- c("PredictedAttrition", "ID")

attr_results_df

write.csv(attr_results_df, paste("C:/Users/bejes/OneDrive/School/Case2PredictionsBergerAttrition.csv"))



```

```{r}
#CLASSIFYING USING NB
splitPercent = .75
      
yes_DF = attr_train_DF %>% filter(Attrition == "Yes")
no_DF = attr_train_DF %>% filter(Attrition == "No")
new_attr_train_DF = rbind(yes_DF,sample_n(no_DF,140))


trainIndices = sample(1:870,round(splitPercent*870))
train = new_attr_train_DF[trainIndices,]
test = new_attr_train_DF[-trainIndices,]
    
model = naiveBayes(train[,c(10,28,29)],train$Attrition)
CM = confusionMatrix(table(predict(model,test[,c(10,28,29)]),test$Attrition))

CM$byClass[1]
CM$byClass[2]
CM$overall[1]

```


```{r}

#Read in Income Data
income_test_DF =  read.csv("C:/Users/bejes/OneDrive/School/MSDS 6306 Doing Data Science/Github Resources/MSDS_6306_Doing-Data-Science-Master/Unit 14 and 15 Case Study 2/EmployeeAttritionAndSalaries/CaseStudy2CompSet No Salary.csv")

income_test_DF

income_test_DF$Gender = ifelse(income_test_DF$Gender=="Female",1,0)



Model1_fit = lm(MonthlyIncome ~ DistanceFromHome + JobLevel + TotalWorkingYears + YearsAtCompany, data = attr_train_DF)
summary(Model1_fit)

attr_train_DF %>% ggplot(aes(x=predict(Model1_fit), y= MonthlyIncome,color = JobLevel)) + geom_point()+
     labs(x = "Predicted Monthly Income", y = "Actual Monthly Income", fill = "JobLevel") +
     ggtitle("Predicted vs. Actual Income")+ geom_smooth(method="lm") 

predMonthlyIncomes = predict(Model1_fit, newdata = income_test_DF)
pred_df = as.data.frame(predMonthlyIncomes,income_test_DF)
pred_df$ID = income_test_DF[,1]

pred_df



```



```{r}
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#
library(tidyverse)
library(aws.s3)
library(caret)
library(e1071)
library(class)
library(dplyr)
library(plotly)
library(ggthemes)
library(car)



# Define UI for data upload app ----
ui <- fluidPage(

  
  # App title ----
  titlePanel("Case Study 2 Shiny App"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      radioButtons("radio2", label = h3("Choose Explanatory Variables"),
                   choices = list("Age" = 1, "JobRole" = 2,"DistanceFromHome" =3, "TotalWorkingYears" = 4,"YearsAtCompany" = 5), 
                   selected = 1),
      
      hr(),
      fluidRow(column(3, verbatimTextOutput("value")))
      
    ),
    
  
    
    # Main panel for displaying outputs ----
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput(outputId = "distPlot"),
      verbatimTextOutput("summary")
    )

  )
)


# Define server logic required to draw a histogram ----
server <- function(input, output) {


attrition_plot = ggplot(data = attr_train_DF,aes(x=Attrition,fill = Attrition)) + geom_bar() + theme_wsj()
  
  
  #FIRST PLOT AREA
 
    
       output$distPlot <- renderPlot({
         
           if(input$radio2 == 1){
            attrition_plot + facet_wrap(~Age)
            
           }
           
           else if(input$radio2 == 2){
            attrition_plot + facet_wrap(~JobRole)
           }
           else if(input$radio2 == 3){
            attrition_plot + facet_wrap(~DistanceFromHome)
           }
           else if(input$radio2 == 4){
            attrition_plot + facet_wrap(~TotalWorkingYears)
           }
           else if(input$radio2 == 5){
            attrition_plot + facet_wrap(~YearsAtCompany)
           }
         
          
        })
     
    
    
}
  
  



shinyApp(ui, server)


```
